name: Flutter WebをGitHub Pagesにデプロイする

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリのチェックアウト
        uses: actions/checkout@v3

      - name: Flutterのセットアップ
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: 依存関係の取得
        run: flutter pub get

      - name: Web版のビルド
        run: flutter build web --release --base-href "/my_first_app/"

      - name: GitHub Pagesへデプロイ
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
